apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mydeploys.customcrd.com
spec:
  group: customcrd.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: mydeploys
    singular: mydeploy
    kind: MyDeploy
    shortNames:
    - md
